<?php

namespace App\Filament\Resources\OrdersResource\Pages;

use App\Filament\Exports\OrderExporter;
use App\Filament\Resources\OrdersResource;
use Filament\Actions;
use Filament\Actions\ExportAction;
use Filament\Resources\Pages\ListRecords;

class ListOrders extends ListRecords
{
    protected static string $resource = OrdersResource::class;

    protected static ?string $title="";
    protected function getHeaderActions(): array
    {
        return [
//            Actions\CreateAction::make(),
            ExportAction::make()
                ->exporter(OrderExporter::class)

        ];
    }

//    protected static string $view='filament.orders.show';

    protected function getHeaderWidgets(): array
    {
        return[
            OrdersResource\Widgets\OrdersWidget::class
        ]; // TODO: Change the autogenerated stub
    }



    protected function getViewData(): array
    {
        return ['table'=>$this->table]; // TODO: Change the autogenerated stub
    }


}
